services:
  database:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: supertokens_user
      MYSQL_PASSWORD: somePassword
      MYSQL_DATABASE: supertokens
    ports:
      - 10000:3306
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-mysql:9.0.2
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 10001:3567
    environment:
      MYSQL_CONNECTION_URI: mysql://supertokens_user:somePassword@database:3306/supertokens
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.Dockerfile
    container_name: supertokens_frontend
    networks:
      - app_network
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "start"]
    ports:
      - 10002:3000

  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.Dockerfile
    container_name: supertokens_backend
    networks:
      - app_network
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 10003:5000

networks:
  app_network:
    driver: bridge
