services:
  database:
    image: mysql:8.4.0
    container_name: supertokens_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: supertokens_user
      MYSQL_PASSWORD: somePassword
      MYSQL_DATABASE: supertokens
    ports:
      - 10000:3306
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-mysql:9.1.2
    container_name: supertokenscore
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 10001:3567
    environment:
      MYSQL_CONNECTION_URI: mysql://supertokens_user:somePassword@database:3306/supertokens
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.Dockerfile
    command: ["npm", "run", "dev"]
    container_name: supertokens_frontend
    networks:
      - app_network
    ports:
      - 10002:3000
    working_dir: /app
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.Dockerfile
    container_name: supertokens_backend
    networks:
      - app_network
    ports:
      - 10003:5000
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./configurations:/configurations

networks:
  app_network:
    driver: bridge
